spring.application.name=demo

# Supabase PostgreSQL 연결 설정
spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.tscywhubhgyaqinfryqc
spring.datasource.password=13754786as!
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA 설정
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# DB 검증 설정
spring.jpa.hibernate.ddl-auto=validate

# 기본 스키마 admin 설정
spring.jpa.properties.hibernate.default_schema=admin