spring.application.name=demo

# PostgreSQL DB 연결 설정
spring.datasource.url=jdbc:postgresql://localhost:5432/MovieProjectDB
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA 설정 (SQL 쿼리 콘솔 출력 및 가독성 높이기)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# DB 검증 설정
spring.jpa.hibernate.ddl-auto=validate

# 💡 [추가] 기본 스키마를 admin으로 설정 (이거 추가하면 Entity에서 schema = "admin" 생략 가능!)
spring.jpa.properties.hibernate.default_schema=admin

