spring.application.name=demo

# Supabase Session Pooler (IPv4 호환)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres?sslmode=require&currentSchema=admin,public}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.tscywhubhgyaqinfryqc}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:13754786as!}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate 설정
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# DB 검증 설정
spring.jpa.hibernate.ddl-auto=validate

# 기본 스키마 admin 설정
spring.jpa.properties.hibernate.default_schema=admin